apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: HellAPP1
      app.kubernetes.io/component: HellAPP1
      app.kubernetes.io/instance: HellAPP1
    name: HellAPP1
  spec:
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: HellAPP1
    template:
      metadata:
        labels:
          deploymentconfig: HellAPP1
      spec:
        containers:
        - image: HellAPP1
          imagePullPolicy: Always
          name: HellAPP1
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 80
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - kylie-fan-club
        from:
          kind: ImageStreamTag
          name: HellAPP1:test
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: HellAPP1
      app.kubernetes.io/component: HellAPP1
      app.kubernetes.io/instance: HellAPP1
    name: HellAPP1
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: HellAPP1
      app.kubernetes.io/component: HellAPP1
      app.kubernetes.io/instance: HellAPP1
    name: HellAPP1
  spec:
    port:
      targetPort: 80-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: HellAPP1
      weight: 100
    wildcardPolicy: None
